REM INSERTING into FINEPAYMENTS
SET DEFINE OFF;
Insert into FINEPAYMENTS (FINE_ID,LOAN_ID,AMOUNT,PAYMENT_DATE) values (1,5,50,to_date('02-04-24','DD-MM-RR'));
Insert into FINEPAYMENTS (FINE_ID,LOAN_ID,AMOUNT,PAYMENT_DATE) values (2,12,100,to_date('12-04-24','DD-MM-RR'));
Insert into FINEPAYMENTS (FINE_ID,LOAN_ID,AMOUNT,PAYMENT_DATE) values (3,19,75.5,to_date('01-05-24','DD-MM-RR'));
Insert into FINEPAYMENTS (FINE_ID,LOAN_ID,AMOUNT,PAYMENT_DATE) values (4,25,40,to_date('18-05-24','DD-MM-RR'));
Insert into FINEPAYMENTS (FINE_ID,LOAN_ID,AMOUNT,PAYMENT_DATE) values (5,30,60.75,to_date('05-06-24','DD-MM-RR'));
Insert into FINEPAYMENTS (FINE_ID,LOAN_ID,AMOUNT,PAYMENT_DATE) values (6,35,25,to_date('20-06-24','DD-MM-RR'));
Insert into FINEPAYMENTS (FINE_ID,LOAN_ID,AMOUNT,PAYMENT_DATE) values (7,42,80,to_date('02-07-24','DD-MM-RR'));
Insert into FINEPAYMENTS (FINE_ID,LOAN_ID,AMOUNT,PAYMENT_DATE) values (8,47,120,to_date('15-07-24','DD-MM-RR'));
Insert into FINEPAYMENTS (FINE_ID,LOAN_ID,AMOUNT,PAYMENT_DATE) values (9,50,45,to_date('01-08-24','DD-MM-RR'));
Insert into FINEPAYMENTS (FINE_ID,LOAN_ID,AMOUNT,PAYMENT_DATE) values (10,1,65,to_date('10-08-24','DD-MM-RR'));
